name: Build Windows Executable

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pyinstaller pandas

      - name: Build executable
        run: |
          python build_windows.py

      - name: Check if executable exists
        run: |
          if (Test-Path "dist/NormalizadorCSV.exe") {
            Write-Host "Executable created successfully"
          } else {
            Write-Host "Error: Executable not found"
            exit 1
          }

      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: NormalizadorCSV
          path: dist/NormalizadorCSV.exe
          retention-days: 5
